### ISSUE TITLE
PyCharm doesn't warning

### ISSUE THREAD

**Issue by MrMarvel** [gri-gus/decohints#1]
```python
from functools import wraps


from functools import wraps

from decohints import decohints


@decohints
def decorator_without_params(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            result = func(*args, **kwargs)
        except Exception:
            print("Error")
            return
        return result

    return wrapper


@decorator_without_params
def test(a: int, b: int) -> int:
    return a + b


test()

```
![image](https://user-images.githubusercontent.com/24212110/174493825-056ec6f7-74c2-440c-96f8-cb1bb20e8ae7.png)

**Comment by gri-gus** [comment]
Hello @MrMarvel, thanks for finding the bug. The issue with Mypy has been fixed in version 1.0.5. It is already available for download. PyCharm will not warn you about an incorrectly called function, as some decorators may inject parameters into the called function. But PyCharm suggests what parameters can be passed to the function. To do this, write `test(` and wait.
